### ISSUE TITLE
Update 2965D Template

### ISSUE THREAD

**Issue by dgscwhite** [mjennings061/viking-log-keeper#45]
As a user I want to update 2965D template to show an error to the FoA when entering a name in the 2nd pilot column that isn't one of our aircraft commanders where the duty is SCT or SCT U/T.

**Comment by mjennings061** [comment]
Bump @dgscwhite 

Stretch goal is to add a print-screen view. Cc @DAbbott99 who has made a template already. Could you share it here Daniel?
