### ISSUE TITLE
Aircraft AF launches require tracking

### ISSUE THREAD

**Issue by mjennings061** [mjennings061/viking-log-keeper#5]
As a stats bitch, I want to keep a track of the total number of aircraft launches after the day, so that I can submit the GUR without missing my flight home on a Sunday afternoon

**Comment by mjennings061** [comment]
Could possibly create a separate collection called `aircraft` with the following fields:

1. Launches
2. Total hours

**Comment by CameronMacG** [comment]
Best bet would be to have a seperate collection as you have said purely for tracking the aircraft stats. Within the collection, have it collect the date, aircraft, launches that day and the total hours and then we can link that back to the exisiting collection. (Cant remember the name of it for the life of me just now....derp!)

**Comment by mjennings061** [comment]
Suggestion to create several tables based on the DB collection `log_sheets`:

1. A table for each aircraft to mimic the F724. This can be generated from the excel file by extracting the "Launches C/F from F724" cell
